# -*- coding: utf-8 -*-
"""Index consolidated_050925_Preprocess.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xJZrB5baxs_1CDwqU31gKa1Milel5NeU
"""

# ===============================================
# Google Colab: Read Excel + Clean Text (Legal/Policy Data)
# Goal: Upload Excel → Identify two columns → Clean text → Export cleaned CSV
# ===============================================

# ---- 1. Install required packages ----
!pip -q install pandas openpyxl

import re
import pandas as pd
from io import BytesIO
from google.colab import files

# ---- 2. Upload Excel file  ----
# This cell will prompt you to select and upload an .xlsx file from your computer
print("Please upload your Excel file (.xlsx):")
upload = files.upload()
assert len(upload) == 1, "Please upload only one file at a time"
fname = list(upload.keys())[0]
print("Uploaded:", fname)

# ---- 3. Helper functions ----
def _normalize_cols(cols):
    """
    Normalize column names:
    - Convert to lowercase
    - Collapse multiple spaces into one
    - Remove leading/trailing spaces
    Returns a dict mapping normalized -> original column name
    """
    return {re.sub(r"\s+", " ", c.strip().lower()): c for c in cols}

def pick_col(df, explicit_name, fallbacks):
    """
    Select a column name in a robust way.
    - explicit_name: exact column name (case-insensitive)
    - fallbacks: list of alternative names to try
    """
    norm = _normalize_cols(df.columns)
    key = re.sub(r"\s+", " ", explicit_name.strip().lower()) if explicit_name else None
    if key and key in norm:
        return norm[key]
    for fb in fallbacks:
        k = re.sub(r"\s+", " ", fb.strip().lower())
        if k in norm:
            return norm[k]
    raise KeyError(f"Column not found. Tried: {[explicit_name]+fallbacks}, existing columns: {list(df.columns)}")

def clean_text_soft(s: str) -> str:
    """
    Gentle text cleaning (recommended for legal/policy text)
    Purpose: remove noise but keep key information such as law numbers and act names.
    Steps:
    - Normalize whitespace
    - Remove URLs and email addresses
    - Remove long numeric IDs and years (usually page numbers)
    - Remove most punctuation, but keep '-' and '/' (e.g., "cross-border", "import/export")
    - Lowercase English text
    """
    if not isinstance(s, str):
        return ""
    t = s.strip()

    # Normalize spaces, tabs, newlines
    t = re.sub(r"[ \t\r\n]+", " ", t)

    # Remove URLs and email addresses
    t = re.sub(r"https?://\S+|www\.\S+", " ", t)
    t = re.sub(r"\b[\w\.-]+@[\w\.-]+\.\w+\b", " ", t)

    # Remove long numbers (4+ digits) and years like 2010, 2021
    t = re.sub(r"\b(19|20)\d{2}\b", " ", t)
    t = re.sub(r"\b\d{4,}\b", " ", t)

    # Remove punctuation except '-' and '/'
    t = re.sub(r"[^\w\s\-/]", " ", t)

    # Lowercase
    t = t.lower()

    # Collapse multiple spaces
    t = re.sub(r"\s+", " ", t).strip()
    return t

# ---- 4. Read Excel file ----
# Automatically pick the first sheet if not specified
xls = pd.ExcelFile(fname, engine="openpyxl")
sheet_name = xls.sheet_names[0]
df = pd.read_excel(fname, sheet_name=sheet_name, engine="openpyxl")

# --- Pick label and text columns (robust to name variations) ---
pillar_col   = pick_col(df, explicit_name="", fallbacks=["Pillar_ID","pillar_id"])
indicator_col = pick_col(df, explicit_name="", fallbacks=["Indicator_ID","indicator_id"])
text_col     = pick_col(df, explicit_name="", fallbacks=[
    "Impact or comments on Acts or practices","impact","text","notes","content"
])

# --- Keep all three relevant columns ---
df = df[[pillar_col, indicator_col, text_col]].rename(columns={
    pillar_col: "Pillar_ID",
    indicator_col: "Indicator_ID",
    text_col: "text_raw"
})

# ---- 5. Basic cleanup: remove empty or duplicate rows ----
# Convert columns to string
df["Pillar_ID"] = df["Pillar_ID"].astype(str)
df["Indicator_ID"] = df["Indicator_ID"].astype(str)
df["text_raw"] = df["text_raw"].astype(str)

# Normalize whitespace in text
df["text_raw"] = df["text_raw"].str.replace(r"\s+", " ", regex=True).str.strip()

# Remove empty or 'nan' rows
df = df[(df["text_raw"] != "") & (df["text_raw"].str.lower() != "nan")]

# Drop duplicates (based on all three columns)
df = df.drop_duplicates(subset=["Pillar_ID", "Indicator_ID", "text_raw"], keep="first").reset_index(drop=True)

# ---- 6. Apply cleaning function ----
df["text_clean"] = df["text_raw"].map(clean_text_soft)

# ---- 5. Basic cleanup: convert types, normalize text, and remove duplicates ----

# Convert columns to string type to avoid NaN or numeric type issues
df["Pillar_ID"]    = df["Pillar_ID"].astype(str)
df["Indicator_ID"] = df["Indicator_ID"].astype(str)
df["text_raw"]     = df["text_raw"].astype(str)

# Normalize whitespace: replace multiple spaces, tabs, or newlines with a single space
df["text_raw"] = df["text_raw"].str.replace(r"\s+", " ", regex=True).str.strip()

# Remove empty or "nan" rows in text column
df = df[(df["text_raw"] != "") & (df["text_raw"].str.lower() != "nan")]

# Remove duplicate rows based on the combination of Pillar_ID, Indicator_ID, and text_raw
df = df.drop_duplicates(subset=["Pillar_ID", "Indicator_ID", "text_raw"], keep="first").reset_index(drop=True)

# ---- Optional: create a label column (use Pillar_ID as label for modeling) ----
df["label"] = df["Pillar_ID"]

# ---- Apply text cleaning to the raw text column ----
df["text_clean"] = df["text_raw"].map(clean_text_soft)

# ---- Display preview (first 3 rows) ----
print("Data reading and cleaning completed.")
print("Number of records:", len(df))
print("Preview (first 3 rows):")
display(df.head(3)[["label", "Indicator_ID", "text_raw", "text_clean"]])

# Save cleaned dataset to CSV
out_path = "cleaned_texts.csv"
df.to_csv(out_path, index=False, encoding="utf-8-sig")
print(f"Cleaned file saved as: {out_path}")

# Provide download link inside Colab
files.download(out_path)
